### ISSUE TITLE
[OTHER] "USE CASES" FOR ABBREVE TERMS

### ISSUE THREAD

**Issue by theselaw** [Njong392/Abbreve#100]
### What would you like to share?

I think "use cases" could be added to the terms to give users more insight into the term to those who are new to it and as an illustration.

**Comment by theselaw** [comment]
this could be added to the db.json files as "use cases".

**Comment by Njong392** [comment]
> this could be added to the db.json files as "use cases".

We are currently adjusting the structure of the database. You can check out the conversation at issue #46

**Comment by Njong392** [comment]
Discussion for this is already going on in #42 I am going to close this issue, and you can move this conversation there :+1:
