### ISSUE TITLE
[FEATURE] Add error msg when non-existing abbreviation is searched AFTER db.json has been fetched once

### ISSUE THREAD

**Issue by adropofilm** [Njong392/Abbreve#102]
### Description

Let's talk through a few different scenerios:

1. When user types in value for an existing abbreviation and then clicks the search button, the definition appears as expected.
![Screen Recording 2022-10-07 at 12 28 09 AM](https://user-images.githubusercontent.com/9134674/194474306-adc2556e-8ca8-4a8d-9e8b-5eefd9ef14b4.gif)

2. If user types in the following AFTER db.json has already been fetched once:
    a. An existing abbreviation, it appears as expected without having to press the submit button. 
    b. However when a user types in an abbreviation that doesn't exist in db.json, nothing appears, no error message, etc.
![Screen Recording 2022-10-07 at 1 05 03 AM](https://user-images.githubusercontent.com/9134674/194478992-8a21c845-e056-441e-81c1-dd564f49f3e5.gif)

How do we want to handle the scenerios for 2a & 2b? Here are possible solutions:
1. Prevent auto filtering onChange of the text input. However, if we do this, we can only search after the **submit** button is pressed, and we'd have to continuously fetch db.json.
2. Allow auto filtering on onChange of the text input, but display error message if definition isn't found in the db.

I propose the 2nd condition as a fix to the problem. Thoughts?

**Comment by Njong392** [comment]
With the new structure of the db that we merged some time ago, I think this problem could be fixed. The browser will have to fetch whatever the user has entered, so submit will be hit after every entry. If they enter something that doesn't exist, hitting submit will then show an error message. How's that?

**Comment by adropofilm** [comment]
Sounds good, let me close this :)
