### ISSUE TITLE
[DOCS] Markdown link to gif is showing in the README

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#103]
### Description

The screenshot in the README was recently substituted by a GIF. But the markdown link of the added GIF is showing in the README, and this doesn't look very good. You can see the link above the gif itself.

Open the README file in edit mode (You have to fork the repo to do this) and in the section where the gif is added, and change 

`![Gif of form section of page with 'various types into the search bar, it's meaning below it, and alternative meanings](![abbr](https://user-images.githubusercontent.com/12339188/194400070-58974868-221c-40fe-9f73-c19d22f764db.gif)` to

`![Gif of form section of page with 'various types into the search bar, it's meaning below it, and alternative meanings](https://user-images.githubusercontent.com/12339188/194400070-58974868-221c-40fe-9f73-c19d22f764db.gif)`

### Screenshots

![Screenshot from 2022-10-07 11-23-49](https://user-images.githubusercontent.com/81039882/194533049-34fb8365-bcde-411d-bce8-56a44a85f9ea.png)

**Comment by sujal-goswami** [comment]
hello, Njong I want to solve this issue can you assign this issue to me, and I also want you to add hacktoberfest label also.

**Comment by Njong392** [comment]
> hello, Njong I want to solve this issue can you assign this issue to me, and I also want you to add hacktoberfest label also.

Unfortunately, this issue doesn't count toward hacktoberfest. You can still go ahead and work on it for good practice. Should I assign you still?

**Comment by sujal-goswami** [comment]
Yeah, sure

**Comment by The-True-Hooha** [comment]
Hello @Njong392 , any result on this? If nothing yet, kindly assign it to me

**Comment by Njong392** [comment]
> Yeah, sure

@sujal-goswami are you still interested in this?

**Comment by sujal-goswami** [comment]
Yes, probably you got PR today.
