### ISSUE TITLE
Involuntary form submit

### ISSUE THREAD

**Issue by JexXxika** [Njong392/Abbreve#109]
### What would you like to share?

I noticed the meaning of abbreviations gets rendered before clicking the submit button

**Comment by Njong392** [comment]
Yes, but we are trying to create a new structure for this. If you check, we have another branch called `structure` that will change the way these abbreviations are stored. With each slang in its own file, the user will need to hit submit every time they search for something.

**Comment by adropofilm** [comment]
Closing this because update was merged that prevents this from occurring.
