### ISSUE TITLE
[OTHER] Abbreves to add

### ISSUE THREAD

**Issue by bigupjeff** [Njong392/Abbreve#11]
### What would you like to share?

TBH - To Be Honest
ROFL - Rolling Around Floor Laughing
FFS - For F*ck Sake

**Comment by Njong392** [comment]
> ### What would you like to share?
> TBH - To Be Honest ROFL - Rolling Around Floor Laughing FFS - For F*ck Sake
> 
> ### Additional information
> _No response_

Go right ahead and add these. I'll assign you.

**Comment by Njong392** [comment]
Hey @bigupjeff if you are still keen on working on this, then you must know that pull requests have already been opened for `tbh`. `rofl` already has an entry. So you are left with `ffs`.

**Comment by bigupjeff** [comment]
@Njong392 Sorry, this issue is a result of me being half asleep on a train messing with Github on my phone. 🙃

Creating PR now
