### ISSUE TITLE
[OTHER] When you run npm install, package-lock.json is updated

### ISSUE THREAD

**Issue by ctoffanin** [Njong392/Abbreve#112]
### What would you like to share?

When the version number is updated in `package.json`, `npm install` should be run to update `package-lock.json` with the new version number and add it to the commit.

In this way, in case of a first-timer willing to contribute to a "good first issue" won't be confused from the get-go with a modified file they are not supposed to commit.

**Comment by ctoffanin** [comment]
Adding it to a git pre-commit hook something like:
"check if `package.json` had been modified and in case run this `npm i --package-lock-only`"
The `--package-lock-only` argument will only update the `package-lock.json`, instead of checking node_modules and downloading dependencies.

I'm not super skilled with git hooks, if you don't find anybody else to work on this, you can assign it to me.
I don't promise you to fix it tomorrow though.

**Comment by adropofilm** [comment]
I'll take a stab at it! I don't know much about git hooks either but I'll document thoroughly for us @ctoffanin

**Comment by ctoffanin** [comment]
Good, if you have problems ping me (I'm sure it won't happen)

**Comment by adropofilm** [comment]
PR ready! Can I pls get some eyes on it? https://github.com/Njong392/Abbreve/pull/127 

@Njong392 @ctoffanin @mathiasayivor
