### ISSUE TITLE
Add '_blank' attribute

### ISSUE THREAD

**Issue by TreciaKS** [Njong392/Abbreve#115]
### Description

It would be great to add a _blank attribute to the site so that when clicking on the github icon, it opens a new tab instead of just opening the Github page on your current website

### Screenshots

<img src="https://user-images.githubusercontent.com/82657928/194859337-2642b20c-e590-43df-a089-d6ff656cb63d.gif" />

**Comment by Njong392** [comment]
This makes sense. Should I assign you?

**Comment by TreciaKS** [comment]
Yes and label my PRs as Hacktoberfest 🙏

**Comment by Njong392** [comment]
> Yes and label my PRs as Hacktoberfest pray

you can go ahead and work on this, but you must know that not every PR you make counts for hacktoberfest :+1:

**Comment by Njong392** [comment]
@TreciaKS is there any update on this?

**Comment by Njong392** [comment]
Closing this as complete.
