### ISSUE TITLE
[FEATURE] Improved UI

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [Njong392/Abbreve#13]
### Description

Improve Ui for mobile state as well as a few changes for desktop state.
The UI right now is awesome but could use a little fixes here and there

### Screenshots
![Screen Shot 2022-10-03 at 12 58 00 PM](https://user-images.githubusercontent.com/82924100/193571833-be3e80e0-f5ad-40b2-b6ab-455699429217.png)

### Additional information

I'll love to take this on 💪🏼

**Comment by Njong392** [comment]
Could you highlight the specific areas that need updating?

**Comment by Onyelaudochukwuka** [comment]
The Search Bar and how results are displayed

**Comment by Njong392** [comment]
> The Search Bar and how results are displayed

I think you should have a go at this. Let's see. I'll assign you because I do think the search bar could be worked upon.

**Comment by Onyelaudochukwuka** [comment]
On it 💪🏼

**Comment by Njong392** [comment]
@Onyelaudochukwuka are there any updates on this?

**Comment by Onyelaudochukwuka** [comment]
None yet🤧

**Comment by Onyelaudochukwuka** [comment]
I'll be turning something in on friday

**Comment by Njong392** [comment]
@Onyelaudochukwuka I apologize if this is too much pressure, but is it safe to close this issue?

**Comment by Onyelaudochukwuka** [comment]
Yes it is
