### ISSUE TITLE
[SUGGESTION] Refactor Issue Templates

### ISSUE THREAD

**Issue by slim-codes** [Njong392/Abbreve#131]
### What would you like to share?
- Consider deleting links that may be confusing to contributors

**Comment by slim-codes** [comment]
> I think the idea of a discord community is a bit far-fetched at this point. It's a small project, and setting up a discord is a whole other universe. If we created our own issue templates, would it help remove the EddieHub links? 

Yeah! That's true though
Surely! The links can be edited out of the templates to avoid confusion.

**Comment by Njong392** [comment]
Do you want to go for it? Maybe create new issue templates?

**Comment by slim-codes** [comment]
Sure! I'd be happy to do so.
I'll just edit it instead. Also, if there are any categories. missing I'll append them to the current template
