### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by adropofilm** [Njong392/Abbreve#133]
### What would you like to share?

When you search for an abbreve that doesn't exist in the db.json, the following occurs:
1. The entire "Start by entering a slang," and search input area shifts left
2. The width in px of the <div> containing the search and the results expands 200+ pixels. 

**Behavior shown in gif below:**
![Screen Recording 2022-10-14 at 6 12 15 PM](https://user-images.githubusercontent.com/9134674/195956468-ee3698d7-2e72-4a8e-a1a5-e25d41f03e34.gif)

**Proposed Solution:**
- Refactor so the search box and the div containing it + the results does not expand and push everything left.
- Maintain the functionality & readability of the results. Word wrap the results, somehow?

**I would like to work on this.**

**Comment by ctoffanin** [comment]
Isn't this the same as #88?

**Comment by adropofilm** [comment]
Welp. I completely forgot that exist, good catch @ctoffanin. Closing now LOL
