### ISSUE TITLE
[DOCS] <Update Todo>

### ISSUE THREAD

**Issue by Aysuarex** [Njong392/Abbreve#135]
### Description

The "HOW TO" readme in public/server has a TODO that says you need to add instructions r contributing to the main readme. This has already been done actually. Should I update the README (I mean the one in public/server)?

### Screenshots

![Screenshot_20221016-182308](https://user-images.githubusercontent.com/99369085/196049262-478d1a29-d860-4a90-8790-16beb5539c08.jpg)

**Comment by Njong392** [comment]
There have been some major updates. With the new merge, this is no longer an issue. I think it's okay to close this issue. What do you think?

**Comment by Aysuarex** [comment]
That's fine. Since it's been solved 👌🏾
