### ISSUE TITLE
DOCS: Change all `slangs` in README to `slang`

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#137]
### Description

The word `slang` isn't really exactly a word if I'd say. So it's strange that we are coining a plural form for it. In the README.md file of the project, all occurrences of `slangs` should be changed to `slang`

**Comment by sebastianmariani** [comment]
Hey @Njong392, I would love to help. :)

**Comment by Njong392** [comment]
Awesome! I've assigned you. Go for it :fire:
