### ISSUE TITLE
DOCS: Change letter in README to lowercase and add `it` to a sentence

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#138]
### Description

From the screenshot below, some part of the phrase in the README.md dos not read correctly. Change the below phrase from;

'Before adding an abbreviation, please make sure that the new entry does Not already exist. You can easily check this by entering the slang on the [live](https://abbreve.vercel.app/) site to see if gives a result or not.'

To;

'Before adding an abbreviation, please make sure that the new entry does **not** already exist. You can easily check this by entering the slang on the [live](https://abbreve.vercel.app/) site to see if **it** gives a result or not.'

The parts in bold are the words that need to be adjusted/added.

### Screenshots
![Screenshot from 2022-10-17 18-40-08](https://user-images.githubusercontent.com/81039882/196247018-c30e0af8-7741-4d65-93db-a9b6f15bc199.png)

**Comment by Vinitvh** [comment]
Hi, can I work on this?

**Comment by Njong392** [comment]
Sure. Assigning you.
