### ISSUE TITLE
DOCS: Minor Issue in Contributing.md

### ISSUE THREAD

**Issue by slim-codes** [Njong392/Abbreve#139]
### Description

The link for **Basic etiquette** in the image below should point to [Open Source Etiquette](https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette), instead, it is currently pointing to [GitHub for beginners](https://developer.mozilla.org/en-US/docs/MDN/Contribute/GitHub_beginners)

### Screenshots

![Screenshot from 2022-10-17 20-16-18](https://user-images.githubusercontent.com/72257135/196263459-e31a3e44-c473-42aa-b6d6-6120cafbfa77.png)

**Comment by sebastianmariani** [comment]
Happy to work on it :)

**Comment by Njong392** [comment]
Closing this as complete.
