### ISSUE TITLE
BUG: Remove `slangs` on website and replace it with `slang`

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#148]
### Description

The word 'slangs' looks strange in plural, so 'slang' as singular should be used. Replace all occurrences of 'slangs' on the website to 'slang'.

Check in the `hero.jsx` component in the `src` folder for the related page.

### Screenshots

![Section of site with the word 'slangs'](https://user-images.githubusercontent.com/81039882/197185217-c4dd83a1-614f-4821-a70d-b3ca413540a5.png)

**Comment by davidlashlee** [comment]
will you assign this to me? Ill take care of it.
