### ISSUE TITLE
DOCS: Wrong URL in contributing.md

### ISSUE THREAD

**Issue by leonvsc** [Njong392/Abbreve#154]
### Description

There is a wrong URL in the contributing.md file. It refers to a MDN repository instead of your own.

Current:
```
cd Abbreve
git remote add abbreve git@github.com:mdn/content.git
```

Should be:
```
cd Abbreve
git remote add abbreve git@github.com:Njong392/Abbreve.git
```

Shall I fix this?

**Comment by Njong392** [comment]
Eek. That doesn't look good. Go for it @leonvsc Assigning you!
