### ISSUE TITLE
Change a:hover color

### ISSUE THREAD

**Issue by glopzel** [Njong392/Abbreve#16]
### Description

Hi everyone, 
There's not enough contrast between background color and text color when the user hovers over the Get Started link (navbar). 
I don't know if the text could be changed to a lighter color or just not have a change of color on hover since there's already a scale effect.

### Screenshots

Picture of the button on hover:
![hover](https://user-images.githubusercontent.com/74939915/193600534-f901f596-d636-4f2d-be5f-3decaa3b0409.jpg)

**Comment by Njong392** [comment]
Would you like to have a go at this @glopzel ?
