### ISSUE TITLE
[New Abbreviations]

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#172]
### What would you like to share?

I was talking to one of my friend and I got something to add!

- idts - I Don't think So
- idli -  I Don't Like It
- ili - I Like it

**Comment by Njong392** [comment]
Go ahead @rupali-codes :heart: Assigning you!

**Comment by Njong392** [comment]
Hey there @rupali-codes will you be submitting another pull request for this?

**Comment by rupali-codes** [comment]
oh, yeah, sure Emy!
