### ISSUE TITLE
FEATURE: Adjust the way abb. are displayed on mobile.

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#174]
### Description

On mobile devices, around the search button, when a slang is entered the abbreviation falls way below the submit button. Perhaps we could redesign it in such a way that we move the results up to align side by side with the submit button on mobile devices.

See screenshot to see the problem.

### Screenshots

![abbreve-git-fork-ctoffanin-add-spinner-njong392 vercel app_(iPhone SE)](https://user-images.githubusercontent.com/81039882/200203260-c627de0f-cbd1-4b0e-8ac0-a5687ec47f58.png)

**Comment by E-fais** [comment]
Let me try this issue, can you please assign me.

**Comment by Njong392** [comment]
Sure thing @E-fais Assigning you!

**Comment by E-fais** [comment]
Thanks

**Comment by dev-phantom** [comment]
@Njong392 has this issue been solved?

**Comment by Njong392** [comment]
Unfortunately it hasn't. But looking over it again, I think it's okay. What do you think?

**Comment by dev-phantom** [comment]
Hmm🧐
My honest opinion is that the alternative text should no have the same exact color with the main sentence
This looks confusing
At first I thought it was displaying twice don't you think?
And a little margin top to the text

**Comment by Njong392** [comment]
That's a new perspective. I like it 🙌🙌 Will u be taking on this issue? We can try something here. Maybe you can open a draft pull request for it and we can work on it more. How does that sound?

**Comment by dev-phantom** [comment]
Awesome ☺️


Let's make impact 🚀
