### ISSUE TITLE
FEATURE: Add meta info to the site

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#175]
### Description

Currently, when we share the project link on some social media, for example, there is no preview image. It would be nice to have meta information so that when we share the link on Twitter, a nice card is generated with the site preview and a short description.
 
[Here](https://css-tricks.com/essential-meta-tags-social-media/) is a nice reference on meta tags. 

If we do decide to work on this, what images could we use?

**Comment by Hat52** [comment]
I would like to take up this issue.

**Comment by Njong392** [comment]
> I would like to take up this issue.
> 

Go ahead! Assigning you.

**Comment by Hat52** [comment]
@Njong392 can you provide the description and also the preview image.

**Comment by Njong392** [comment]
Image link: https://i.imgur.com/dEy9x91.png
Description: Open-source dictionary for slang.

**Comment by Njong392** [comment]
How far with this @Hat52 ? All good? If you need anything feel free to drop your query here.

**Comment by Hat52** [comment]
I will create a PR by tomorrow. No blockers right now but in case I hit one I will surley ask for help.

**Comment by Njong392** [comment]
But it does for me. Could you try opening it on another browser?
