### ISSUE TITLE
BUG: Change the submit button text to Search

### ISSUE THREAD

**Issue by Hat52** [Njong392/Abbreve#181]
### Description

The text submit does not really clarify if we are submitting a new Abbreve or we are searching for an Abbreve. Replacing the submit text with search would make a lot of sense.

### Screenshots

![image](https://user-images.githubusercontent.com/44437268/200564507-4239192e-88ca-46a8-ae3a-0efc1cfc19d4.png)

**Comment by Njong392** [comment]
Do you want to be assigned to this @Hat52 ?

**Comment by Hat52** [comment]
Yes

**Comment by Njong392** [comment]
Assigned you.

**Comment by Hat52** [comment]
Yes

**Comment by Njong392** [comment]
Closing this as complete.
