### ISSUE TITLE
DOCS: update link for cloning the repo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#186]
### Description

Hi, I just noticed something, the link in CONTRIBUTING.md for cloning is the repo is not working, kindly update it from ```git@github.com:emy/Abbreve.git``` to ```git@github.com:Njong392/Abbreve.git```.

### Screenshots

![image](https://user-images.githubusercontent.com/78981177/201473925-245dfa32-4109-4a97-b066-3ec586a0fc42.png)

**Comment by Njong392** [comment]
Ohhh... that's bad. Assigned you Rupali!

**Comment by rupali-codes** [comment]
Alright Emy! fixed :)
