### ISSUE TITLE
Error handling is not properly optimised

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#2]
### Description

Users should be notified if a record they have entered isn't available in the JSON database yet. This is yet to be worked upon.

**Comment by ctoffanin** [comment]
Emy, can I work on this one?

**Comment by Njong392** [comment]
> Emy, can I work on this one?

Yes, Cristian! Go ahead. I'll assign it to you.

**Comment by ctoffanin** [comment]
Haha. nice, you could assign it to them at least :D

**Comment by Njong392** [comment]
> Haha. nice, you could assign it to them at least :D

They made a change, but they undid it because it didn't work, unfortunately. Do you still wish to work on this?

**Comment by ctoffanin** [comment]
Yeah, sure, not immediately, though.

**Comment by Njong392** [comment]
> Yeah, sure, not immediately, though.

Take your time :) But not too much time lol

**Comment by thisisisheanesu** [comment]
Oh hey, sorry I undid that by mistake and sorry I didn't ask first. Not used to open source stuff. I undid it to avoid mixing up things, the other PR I did was for a typo and I didn't want to send both as one you can verify but it was working when I tried

**Comment by Njong392** [comment]
> @Njong392 is this what you want? [main...ctoffanin:Abbreve:optimise-error-handling](https://github.com/Njong392/Abbreve/compare/main...ctoffanin:Abbreve:optimise-error-handling) Or at least is that your idea?

This looks quite good! You should create a PR!
