### ISSUE TITLE
ABBREVIATION: AISB

### ISSUE THREAD

**Issue by mohammadshaad** [Njong392/Abbreve#201]
### Description

I want to add a new slang abbreviation in the dictionary i.e. AISB which means  "As it should be/as I said before". Kindly assign me this issue so that I can add it into the db directory. Thank you

**Comment by Njong392** [comment]
For adding abbreviations, you can go ahead and create a PR once you're sure that the abbreviation you want to add doesn't already exist. Go ahead @mohammadshaad 🙌 Create that PR! 💣

**Comment by mohammadshaad** [comment]
Thank you so much @Njong392
