### ISSUE TITLE
BUG: little or no padding added && large text on mobile view

### ISSUE THREAD

**Issue by dev-phantom** [Njong392/Abbreve#206]
### Description

There is no padding before those tweets 
And in between the tweets the padding top is much

### Screenshots

![Screenshot_20230110-004925](https://user-images.githubusercontent.com/72051159/211431006-0ebf80a1-f1c6-4800-89f7-33f74f602110.png)

**Comment by dev-phantom** [comment]
I could fix this though 🤷

**Comment by Njong392** [comment]
Yes! Thank you for catching that. Assigning you 💙💙

**Comment by dev-phantom** [comment]
Thanks 

Get ready to merge my PR anytime soon 😊
