### ISSUE TITLE
BUG: the medium screen view is not responsive

### ISSUE THREAD

**Issue by dev-phantom** [Njong392/Abbreve#208]
### There is an issue with responsiveness on the medium screen 
i could fix this also if am assigned to it

### Screenshots

![image](https://user-images.githubusercontent.com/72051159/211655743-db36617b-00b4-437e-85fb-ead29695eaad.png)

**Comment by Njong392** [comment]
:thinking: I'd love to see how you go about this. Assigning you!

**Comment by Njong392** [comment]
Hello @dev-phantom How far with this issue?

**Comment by dev-phantom** [comment]
Am so sorry about this
My PC is currently in bad shape
But I'll get it done before 5th of February


Sorry for the delay

**Comment by Njong392** [comment]
No issues! Take your time, fren 💜

**Comment by dev-phantom** [comment]
> No issues! Take your time, fren 💜

Thanks for understanding 🙏
