### ISSUE TITLE
ABBREVIATION: Got new abbreviations

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#209]
### Description

I got to know some new abbreviations and i wants them to be a part of Abbreve.
1. gtsu - Good To See You(U)
2. gbtul - Get back to You(U) Later
3. gtk - Good to Know/Get to Know/Glad to Know

**Comment by Njong392** [comment]
These look so cool! Assigning you @rupali-codes 🎉

**Comment by rupali-codes** [comment]
HI @Njong392, i wanna confirm something, which one is used more for "You" is it "You" or "U"?

**Comment by Njong392** [comment]
I think "You" would be more appropriate. "U" is sort of an abbreviation on its own already

**Comment by rupali-codes** [comment]
Ahh, okay, we go with You then :)
will make a PR soon
