### ISSUE TITLE
Add new slangs

### ISSUE THREAD

**Issue by AmineAouragh** [Njong392/Abbreve#21]
## New slangs needed 

While I was giving a try to Abbreve, i typed ngl but unfortunately didn't get any results in return - i know the project is still so young but no problem.

Same thing goes for ftw.

**Comment by Njong392** [comment]
This is currently being worked on! The reason the slang didn't show is that the abbreviation for it isn't available yet. You can open a pr to add them.

**Comment by AmineAouragh** [comment]
Oh yeah I know they don't exist yet. Will do ;)

**Comment by Njong392** [comment]
> Oh yeah I know they don't exist yet. Will do ;)

`ngl` was just recently added. If you are still keen on making a contribution, I'd say add only `ftw`
