### ISSUE TITLE
DOCS: <Adding Logo to README.md and a separate Description heading>

### ISSUE THREAD

**Issue by the-amazing-atharva** [Njong392/Abbreve#214]
### Description

Hey,

As a beginner contributor, I am really impressed by the project and I am excited to get involved with this project 

I would like to take on the task of adding a logo to the README.md file and creating a separate "Description" heading. 
I believe that the addition of a logo and distinct heading for the description will greatly improve the overall presentation of the project.
I would appreciate being assigned to this issue so that I can begin contributing to the project.

Regards!

**Comment by the-amazing-atharva** [comment]
Hey, thanks for considering my request.

It will take sometime, but I'll come with a good description after understanding the project and its features.

Should I send a PR when ready or what else can I do to send the description?

**Comment by Njong392** [comment]
Github issues are great for discussions! Once you come up with something, we can always go over it under this issue. You can then go ahead with a PR once we've agreed on something. What do you think?

**Comment by the-amazing-atharva** [comment]
Yeah no worries!!
Actually I am new to the normal workflow of GitHub and Issues/PR so wanted to confirm

Looking forward to writing a good description!!!

Also what do you think about my idea of adding the logo to the README?

**Comment by Njong392** [comment]
There's something called a draft pull request. It's a chance for you to open a pull request for features that you're not sure of. Once the feature is confirmed, you can make the draft PR a real PR. But let's not overwhelm you. We can use this issue for discussion 💜

**Comment by the-amazing-atharva** [comment]
Hey,
Good Morning!!!

I made some changes (added the logo and wrote the description)
**Thoughts?**

![image](https://user-images.githubusercontent.com/121221252/213611357-80335188-b33b-45cd-9677-3b4bf48f1213.png)


I also had this idea to add this screenshot in project overview section, **what do you think?**
![abbreve-transformed](https://user-images.githubusercontent.com/121221252/213611452-7e75b211-9ae7-4c05-af8d-452a1e7c5270.png)

**Comment by Njong392** [comment]
The first one looks really great! I like the bullet points very much. As for the screenshot to add to the overview, I think the short gif we already have suffices. Because it's easy to see through that gif the most crucial feature of the app, that is the search feature. But I like the first one. What do you think?

**Comment by the-amazing-atharva** [comment]
Yeah fair enough

Do I create a PR?

**Comment by Njong392** [comment]
Yes yes. Go ahead with your PR!

**Comment by the-amazing-atharva** [comment]
Thanks!!
