### ISSUE TITLE
Darkmode doesn't stay on refresh.

### ISSUE THREAD

**Issue by PriyansuMaurya** [Njong392/Abbreve#218]
### Description

_I can implement it._

https://user-images.githubusercontent.com/101447544/213721491-880c4fe2-e8d5-4c3e-91bf-4d2468a84d59.mp4

**Comment by Njong392** [comment]
Assigning you! :heart:

**Comment by Lourvens** [comment]
Can I work on it ?

**Comment by PriyansuMaurya** [comment]
> Can I work on it ?

Requesting reassignment to @Lourvens as I am out of my home place.

**Comment by seinlusnyongesa** [comment]
hello, is there any progress being made ? I would like to work on this issue.

**Comment by PerkinsDan** [comment]
> hello, is there any progress being made ? I would like to work on this issue.



> hello, is there any progress being made ? I would like to work on this issue.

@Lourvens is currently actively working on this (quoted his fork 5 hours ago)

**Comment by seinlusnyongesa** [comment]
> @Lourvens is currently actively working on this (quoted his fork 5 hours ago)

ok, I see. wish him good luck

**Comment by Lourvens** [comment]
It's ok now, I'm done with this issue I just forgot to index it in my PR. thanks @PriyansuMaurya for reassign it to me
