### ISSUE TITLE
BUG: cursor barely visible before first character input

### ISSUE THREAD

**Issue by PerkinsDan** [Njong392/Abbreve#220]
### Description

When you first click on the search input field you get a tiny cursor that is barely visible behind the placeholder text

Simple fix. Am happy to do myself. 

TODO: Cursor needs to be bigger and potentially darker / or placeholder text gets lighter when focused

### Screenshots

![Input](https://user-images.githubusercontent.com/84538727/213806573-eb00059c-dbf1-4c53-a73c-fc5b08cd041c.png)

**Comment by Njong392** [comment]
Thanks for picking this up! Assigning you :heart:

**Comment by PerkinsDan** [comment]
After some more investigation, this bug is google chrome specific. Strange...

**Comment by Njong392** [comment]
Really strange. As I've not really paid attention to it lmao. Is there anything we can do?

**Comment by PerkinsDan** [comment]
It should be alright. I need to do a bit more research

**Comment by Njong392** [comment]
I'll look into it too.

**Comment by PerkinsDan** [comment]
This isn't ideal but I couldn't find any other solutions. I tried a number of ways to make the caret bigger by trying to change line height etc. It for some reason starts small and then gets bigger after a character is typed. Yay. we love google chrome :). If i find a solution later on I will be sure to update it

**Comment by Njong392** [comment]
So I think we can close this issue then? Until we find a workable solution.
