### ISSUE TITLE
Increase input field size

### ISSUE THREAD

**Issue by elite16op** [Njong392/Abbreve#232]
### Description

The input field size is small due to which the placeholder text is getting cut off a bit. You can assign me I can do it.
![Screenshot (494)](https://user-images.githubusercontent.com/111674354/214860750-c2ff3316-295f-4063-a28b-7e59b07d8b54.png)

**Comment by Njong392** [comment]
Good catch! Thank you for picking it up. You can go on and open a pull request.

**Comment by dev-phantom** [comment]
has this issue been fixed

**Comment by Njong392** [comment]
It's already been assigned.

**Comment by elite16op** [comment]
I will fix this today for sure.

**Comment by elite16op** [comment]
Kindly check the request made.
