### ISSUE TITLE
BUG: <dark/light mode fix>

### ISSUE THREAD

**Issue by i-am-rita** [Njong392/Abbreve#239]
### Description

Light/dark mode icon can be switched when clicked i.e there should be one icon and a function that changes the icon when it's clicked depending on the switch.

If the icon is on dark mode, when clicked, the icon should change to light mode icon.
Something like this:

https://user-images.githubusercontent.com/69390818/216075003-a49dd932-ac27-4388-93b0-6f2df3242e04.mov

**Comment by Lourvens** [comment]
Sorry @i-am-rita this issue doesn't concern this repo

**Comment by Njong392** [comment]
Hello, @i-am-rita I would love to hear more thoughts on this. Does it affect UX in any way?

**Comment by i-am-rita** [comment]
Hi Njong392,

Yes, it does to me.
A user should not have to move their mouse away from one of the modes to
change it when he/she can stay on one and toggle it.

The light/dark mode acts like a switch. In a house, there isn't a separate
switch for light or dark, it's the same switch.

I hope I was able to explain well.

Kind regards,
Rita

**Comment by Njong392** [comment]
I think in this case we can consider the distance between the buttons. They are close together and would require the same amount of clicks from the user to switch between modes. The UX between both scenarios will not be too different. I understand your point and am trying to do some research.

**Comment by i-am-rita** [comment]
Ok, thanks.

Rita

**Comment by dev-phantom** [comment]
thought about this too 
i might open a PR on this soon

**Comment by Njong392** [comment]
> thought about this too 
> i might open a PR on this soon

Please don't open a PR yet. I still looking into this.

**Comment by dev-phantom** [comment]
> > thought about this too
> > i might open a PR on this soon
> 
> Please don't open a PR yet. I still looking into this.

no prop
you wont merge it it will just be there pending on when you finish looking into it

**Comment by abhiraj-ku** [comment]
Hey @Njong392 I Think this is a good idea to have only one button to change the theme instead of having two buttons. I hope you will look into it.

**Comment by Njong392** [comment]
This issue really skipped my mind already. I'll have a response by the weekend hopefully. In the meantime, who should I assign it to?

**Comment by Lourvens** [comment]
You can assign it to me

**Comment by EOluwaseun** [comment]
In my opinion, having one button controlling the modes would be fantastic for UX. Thanks !

**Comment by priyanshtiwari001** [comment]
Hi @i-am-rita , if no one is working on this, can you please assign to me.  will create a single button that allows the user to toggle between dark and light mode, resulting in the same output as the selected theme.
