### ISSUE TITLE
cfbr: Commenting For Better Reach

### ISSUE THREAD

**Issue by abhiraj-ku** [Njong392/Abbreve#249]
Hey @Njong392 I want to add cfbr:  Commenting For Better Reach which is used a lot on LinkedIn post . Can I open a PR regarding this following all the guidelines for opening a PR.

Thanks in Advance

![cfbr issue](https://user-images.githubusercontent.com/113116498/217863399-9802259c-81bd-45a0-bd42-63c6a0a859c8.PNG)

**Comment by Njong392** [comment]
Go for it! Thank you in advance for this 💜 assigning you.
