### ISSUE TITLE
RSVP: Please respond

### ISSUE THREAD

**Issue by Pratimapal1209** [Njong392/Abbreve#253]
### Description

Hey @Njong392 , 
I want to add a new abbreviation ---> RSVP: Please respond, which is used  at the end of a written invitation.

![Screenshot 2023-02-10 212517](https://user-images.githubusercontent.com/97719941/218137922-2dad8983-86e1-45a2-9249-0f49fd2e98e3.png)

Can i work on it?

**Comment by Njong392** [comment]
Sure thing! I'll assign you to this.

**Comment by Njong392** [comment]
Closing this as fixed.
