### ISSUE TITLE
ABBREVIATION: <description>

### ISSUE THREAD

**Issue by Judge-Paul** [Njong392/Abbreve#256]
### Description

ilysm - I Love You So Much
wuu2 - What Are You Up To
ijn - In Jesus Name
ml - More Life

**Comment by Judge-Paul** [comment]
I would like to add the following words I tried all of them and they are not listed

**Comment by Njong392** [comment]
Sure thing! Go ahead. Assigning you.

**Comment by newdydx** [comment]
@Njong392 Can I work on this issue since it has not been solved...thanks

**Comment by Judge-Paul** [comment]
@newdydx have you worked on the issue

**Comment by newdydx** [comment]
@Judge-Paul If given the permission to do so I will definitely work on it

**Comment by Judge-Paul** [comment]
@Njong392 Please can you unassign me and assign @newdydx

**Comment by Njong392** [comment]
Sure
