### ISSUE TITLE
FEATURE: <Add slang words or phrases>

### ISSUE THREAD

**Issue by yeshwantthota** [Njong392/Abbreve#260]
### Description

Can not we add slang words or phrases in this application?

**Comment by yeshwantthota** [comment]
I mean there are some slangs that are in words(lingos), not abbreviations, so can we add such slang to this website?

**Comment by Njong392** [comment]
An example would be great. I'm sorry, but I am still not catching on.

**Comment by milekboy** [comment]
I think she meant slangs like "bonkers" is a Uk slang for "crazy". Would adding a feature where users can search for slangs and not just abbreviations be nice?

**Comment by Njong392** [comment]
Ah I see. In that case, it won't really be slang. It would be an expression of some sort. I don't really think that's going to fit I'm sorry.
