### ISSUE TITLE
ABBREVIATION: <IKYFL>

### ISSUE THREAD

**Issue by Devanshukoli** [Njong392/Abbreve#271]
### Description

Want to Add: IKYFL = "I Know You Fucking Lying"

**Comment by Devanshukoli** [comment]
Could you please assign it to me? @Njong392

**Comment by Njong392** [comment]
Thanks for the issue! Sure, go ahead and open a pull request.

**Comment by Njong392** [comment]
Okay wait. It seems that when I assigned the issue to you, I wasn't paying attention. Then I saw the PR and thought I had seen the same pull request before haha. I am sorry, it is my mistake.

**Comment by Devanshukoli** [comment]
It's okay. As a Maintainer and person who owns repo. It makes sense it will really hard for you I guess. Though, I really appreciate the effort. Thanks as always. @Njong392 😁👍
