### ISSUE TITLE
ABBREVIATION: <description>

### ISSUE THREAD

**Issue by Yasir-Khan22** [Njong392/Abbreve#284]
### Description

Add an abbreviation for na?

**Comment by Njong392** [comment]
That looks cool. What does it mean?

**Comment by Yasir-Khan22** [comment]
- Not Applicable.
- Not Available.

**Comment by Njong392** [comment]
I seemed to have missed the notification for this. But I think Not Applicable and Not Available is `N/A`, no? If this is the case then it will pose a problem because we can't create file names with slashes in between.

**Comment by Njong392** [comment]
Yes, sure. I will assign you to it.
