### ISSUE TITLE
ABBREVIATION: "TFY"

### ISSUE THREAD

**Issue by Ghasty003** [Njong392/Abbreve#285]
### Description

"tfy" abbreviation doesn't exist yet in the abbreviation database. I'd love to add it.

**Comment by Njong392** [comment]
Sure go ahead and add this. I will assign you. What is the full abbreviation by the way?

**Comment by Ghasty003** [comment]
It means "Thanks For Yielding"
"Yield" in this case means "Reward"
So, basically, it means, "Thanks for the reward"

Would you assign me now?

**Comment by Njong392** [comment]
Go ahead with your PR. Assigning you.

**Comment by Ghasty003** [comment]
> Go ahead with your PR. Assigning you.

I made a PR. Kindly review.
