### ISSUE TITLE
BUG: <description>

### ISSUE THREAD

**Issue by abhijain2003** [Njong392/Abbreve#286]
### Description

The loading when we search for abbreviation, is outside of input panel

dosen't sound good in terms of ui

would be better to have loading inside search button which is by toggling innerText of button with Loading panel

### Screenshots

https://user-images.githubusercontent.com/91718608/222051989-6025826d-8425-442e-b120-678ab8906d14.mp4

**Comment by Njong392** [comment]
I do agree that it seems outside of the input box a little bit. Do you want to propose a fix for this?

**Comment by dev-phantom** [comment]
> I do agree that it seems outside of the input box a little bit. Do you want to propose a fix for this?

Can I get assigned to this?

**Comment by abhijain2003** [comment]
I have already worked on it, waiting for maintainers permission to raise a pr.

**Comment by Njong392** [comment]
Ah sure. Go ahead. Raise your PR

**Comment by abhijain2003** [comment]
Sure ,

Thanks

**Comment by abhijain2003** [comment]
maintainers will you please review my pr and merge it

**Comment by Njong392** [comment]
Sorry for the delay. Please be patient. I'll get to this soon 😀
