### ISSUE TITLE
ABBREVIATION: WCW

### ISSUE THREAD

**Issue by Ghasty003** [Njong392/Abbreve#294]
### Description

This means "Women Crush Wednesday"

**Comment by Njong392** [comment]
Unfortunately, this is not an abbreviation.

**Comment by Ghasty003** [comment]
> Unfortunately, this is not an abbreviation.

For real? You may close this issue then, if so.

**Comment by Ghasty003** [comment]
> Unfortunately, this is not an abbreviation.

For real? You may close this issue then, if so.

**Comment by Njong392** [comment]
Oh no. I commented on the wrong one. I apologize. Please open a pr for this.
