### ISSUE TITLE
FEATURE: <Only Search button should be in center of the page>

### ISSUE THREAD

**Issue by abhiraj-ku** [Njong392/Abbreve#296]
### Description

Hey @Njong392  

We know Google's Main feature is search and so they have search button in the middle of site and nothing else , now in the same way this website is used to search for abbreviations so wouldn't that be great if the site should have only the search button in the center and search result below that .. 
Suggestions are welcome 
I hope you will look into the matter .. Thanks In advance

**Comment by Saikat-Mandal** [comment]
@abhiraj-ku are you working on this issue ?

**Comment by abhiraj-ku** [comment]
@Saikat-Mandal hey 
I am travelling so i can't work on this so  you can work on this issue . Make sure you are assigned this

**Comment by Saikat-Mandal** [comment]
@abhiraj-ku yeh sure

**Comment by Njong392** [comment]
@abhiraj-ku Thank you for opening this issue. It sits in the middle of the page in a way. Except it's really not centralized. I don't see a problem with the way it is now, but you can always open a draft pull request and we check it out together. Although I have to ask, how would this feature affect the overall performance or UX of the site?

**Comment by Njong392** [comment]
Hello everyone. Since no further discussions have been made in relation to this issue, I'll have to close it unfortunately. Hope you all understand.
