### ISSUE TITLE
BUG: <Search bar visibility>

### ISSUE THREAD

**Issue by Shoaib19** [Njong392/Abbreve#298]
### Description

search input field visibility is not clear in light mode 
increasing search input shadow opacity will help.

tested on mac using chrome browser.

### Screenshots

<img width="510" alt="image" src="https://user-images.githubusercontent.com/86943632/223778975-6dca29d5-b275-4022-8e00-03c2a3e3d0ae.png">

**Comment by Njong392** [comment]
I'm curious as how much clearer we can make this. Maybe we can define our opacity level in the tailwind config file? What do you think?

**Comment by Shoaib19** [comment]
Yes, I think shadow at bottom should be more darker, if I get the chance then I should submit sample.

**Comment by Njong392** [comment]
Should I assign this to you so that you open a draft pull request?

**Comment by IM-TECHNO** [comment]
Kindly Assign the Task to me ! :D

**Comment by milekboy** [comment]
I think it can be fixed simply by adding a border

**Comment by Shoaib19** [comment]
Yes it can but if just increase the opacity of the current shadow under the input field it will also work and looks more elegant.
I was almost forgot it I will give it a try this weekend.

**Comment by milekboy** [comment]
![2023-04-10](https://user-images.githubusercontent.com/107077238/230947989-508b62e8-2a7d-4cc6-a0c6-dc0c6039ab35.png)
I think I've fixed this issue, what do you think?
