### ISSUE TITLE
[DOCS] Include code of conduct

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#3]
### Description

We need some rules to make sure that contributors adhere to and collaborate in ways that are suitable for everyone else.

**Comment by akebu6** [comment]
What kind of information would you like to see in your code of conduct, anything in particular that you would want added?
And can I have the issue assigned to me?

**Comment by Njong392** [comment]
Nice! I'll assign this to you. The code of conduct doesn't need much. I think github has a cool template that we could use. It already highlights the rules quite nicely.
