### ISSUE TITLE
DOCS: addition of a section in the readme documentation

### ISSUE THREAD

**Issue by cleverhare** [Njong392/Abbreve#301]
### Description

So, The position of this existing application is just mind blowing but still there should be a section where all the contributors profic pic lies. So if you found this a useful Issue, i will be happy to contribute to it.

**Comment by Njong392** [comment]
Hm. Do you mean adding it to the site itself? Or to the README?

**Comment by cleverhare** [comment]
To the Readme, But its not a bad idea to add it to Actual page as well

**Comment by Njong392** [comment]
Adding it to the README won't be so bad. I don't think adding it to the site improves it in any way though. So I'd prefer that you added it to the README. Would you like to be assigned to this?

**Comment by cleverhare** [comment]
Yes I would love to be assigned

**Comment by Njong392** [comment]
Apologies for the late response to this. You have the go-ahead to work on this issue now.

**Comment by Pratimapal1209** [comment]
If there is no response from him , I would be happy to take over this issue

**Comment by cleverhare** [comment]
I have already raised a PR, but it never got reviewed or accepted

**Comment by Njong392** [comment]
I am really sorry @cleverhare I delayed to review the PR because I was still thinking about the contributors section being on the README. Having contributors add their names to a json... Could you please explain the process to me? Is there some kind of way to then pull those names to be displayed? Apologies for being clueless in this regard.

**Comment by Pratimapal1209** [comment]
> I have already raised a PR, but it never got reviewed or accepted

Ohh okay, I just wanted to try this too
it would be very helpful if you can explain how you did it.

**Comment by wasup-yash** [comment]
@Njong392 Are you saying something like the LinkeFree project on GitHub do  ? That is by Eddiehub org.

**Comment by Njong392** [comment]
@wasup-yash LinkFree project does not have a section in their README listing contributors. That's why I am a little skeptical about this issue. The README for this project is long enough as it is.

**Comment by cleverhare** [comment]
you're correct but I think it would be a motivation for new contributors so we will be able to improve this much more
