### ISSUE TITLE
ABBREVIATION: IFYKYK

### ISSUE THREAD

**Issue by mayukh551** [Njong392/Abbreve#302]
### Description

Meaning: “if you know you know“

**Comment by Njong392** [comment]
this already exists in the database.

**Comment by mayukh551** [comment]
but when i type it in the search bar, this is what it shows me
![image](https://user-images.githubusercontent.com/82811112/225899773-a625e4bc-8761-473d-8010-b4342e687d53.png)

**Comment by Njong392** [comment]
I'm sorry. i must have phrased it wrongly. `If You Know, You Know` already exists in our records as `IYKYK`

**Comment by gulshanpr** [comment]
hey @Njong392, there is a possibility anyone can search between `ifykyk` and `iykyk` because both the short forms are popular on social media, so it would be great if we include both abbreve.
