### ISSUE TITLE
FEATURE: Store all abbreviations in Cloud Firestore with 1GB for Free

### ISSUE THREAD

**Issue by mayukh551** [Njong392/Abbreve#303]
### Description

Storing all abbreviations in cloud instead of storing them in the frontend code. 

As more and more abbreviations will be discovered or invented, more the size of the frontend code will increase.

Instead we should use Cloud Firestore which is a No-SQL database in Firebase that can allow up to 1gb free space of storage.
And if required, payment for extra storage of more than 1GB is also very less.

**Comment by mayukh551** [comment]
I would like to work on this issue.

**Comment by Njong392** [comment]
This has been brought up before. Even though this project is open source, it is also kind of personal. I would love to move the abbreviations to a database, but for now it is not feasible as I don't have time to see into it.

**Comment by mayukh551** [comment]
Ok np

**Comment by Njong392** [comment]
Amazing. Closing this issue then
