### ISSUE TITLE
ABBREVIATION: 

### ISSUE THREAD

**Issue by Yasir-Khan22** [Njong392/Abbreve#322]
### Description

kindly add abbrevation `fka`. It means `formerly known as`.

**Comment by milekboy** [comment]
Can I fix this?

**Comment by milekboy** [comment]
@Njong392 can I fix this?

**Comment by Njong392** [comment]
@milekboy any updates on this maybe?

**Comment by Dmitriy-SP** [comment]
Good day! If the issue is open I would like to take it.

**Comment by Njong392** [comment]
> Good day! If the issue is open I would like to take it.

Sure thing! I got no replies, so I guess it is all yours

**Comment by Dmitriy-SP** [comment]
Ok, then I take it.

**Comment by Yasir-Khan22** [comment]
It seems I have missed the notification for this issue.😞
