### ISSUE TITLE
ttly: Totally

### ISSUE THREAD

**Issue by E-fais** [Njong392/Abbreve#348]
### Description

ttly is the abbreviation for Totally.
![Abbreve - Google Chrome 22-04-2023 10 49 23 AM](https://user-images.githubusercontent.com/102040088/233770782-383fd572-04dc-43da-b492-bd2d028309c2.png)

**Comment by E-fais** [comment]
assign me please , i can work on this issue

**Comment by Njong392** [comment]
You got it!
