### ISSUE TITLE
<ykwim>: <You Know What I mean>

### ISSUE THREAD

**Issue by Yasir-Khan22** [Njong392/Abbreve#356]
Kindly add this abbreviation. `You Know What I mean`.

![image](https://user-images.githubusercontent.com/63096083/234654304-ff50b2fb-ed78-433d-9e53-e476424802d0.png)

**Comment by Njong392** [comment]
Do you want to get assigned to this?

**Comment by Yasir-Khan22** [comment]
@Njong392 
yeah sure!

**Comment by Yasir-Khan22** [comment]
Hey! @Njong392 I think the caret cursor on text field is too small before typing anything on it, and if we highlight it it seems to be rounded. Should I raise another PR for this?

See attachment Here: 👇 

https://user-images.githubusercontent.com/63096083/234796624-b3578c90-f400-4e3e-b70e-3b6ebbef462e.mp4

**Comment by Njong392** [comment]
🤔 sure thing. Go ahead and open a pr for both changes then.

**Comment by Njong392** [comment]
closing this as complete
