### ISSUE TITLE
BUG: <The caret cursor on text field is too small before typing anything inside it.>

### ISSUE THREAD

**Issue by Yasir-Khan22** [Njong392/Abbreve#357]
### Description

Before typing anything inside the text field, the caret cursor is too tiny, and then when we highlight it, it seems rounded. 

### Screenshots

https://user-images.githubusercontent.com/63096083/234796624-b3578c90-f400-4e3e-b70e-3b6ebbef462e.mp4

**Comment by Yasir-Khan22** [comment]
@Njong392 
Assign this to me I'll notify you for a review request.

**Comment by Yasir-Khan22** [comment]
See Attachment Here 👇 

https://user-images.githubusercontent.com/63096083/235229097-79328684-9f06-4929-9d2a-b4440b95b158.mp4

**Comment by Njong392** [comment]
Looks great! ⭐ Did you open a PR for it? You can open a PR if you like.

**Comment by Yasir-Khan22** [comment]
@Njong392 
You can check and merge it. I've already raised a PR for it.

**Comment by Yasir-Khan22** [comment]
I'll inform you soon for review request.
