### ISSUE TITLE
When abbreviation is shown, error message doesn't disappear

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#37]
### Description

When a slang that does not exist is shown, there is a message to tell user that the slang does not exist. But if the next slang to be entered does exist, the abbreviation is shown. But the error message from the previous entry does not go away.

### Screenshots

![Screenshot from 2022-10-03 22-16-16](https://user-images.githubusercontent.com/81039882/193684993-5209323a-2be5-480a-93ec-43a31ecd9f85.png)

**Comment by TylerGeorgeAlexander** [comment]
Hey, I just requested a PR. I might have accidentally formatted with my prettier linter. 
I got the fix by changing:
```
<input
                type="text"
                placeholder="Search slang full meaning..."
                className="flex-1 w-1/2 h-11 rounded-full ml-2 border-none outline-none text-gray text-lg bg-ash"
                value={userInput}
                onChange={(e) => {
                  setUserInput(e.target.value.toLocaleLowerCase());
                  setErrorMessage("");
                }}
              />
```

It resets the errorMessage state on change to work with the existing code's conditional rendering.
I hope this helps, let me know if there is anything else I could assist with.

**Comment by ctoffanin** [comment]
The codebase has changed, but yes `setErrorMessage(false);` there does the trick.

**Comment by Njong392** [comment]
> It resets the errorMessage state on change to work with the existing code's conditional rendering. I hope this helps, let me know if there is anything else I could assist with.

:thinking: I already used `useEffect` to fix this already. If you try the site now, it should work fine. If you see anything odd, feel free to suggest additions. If not I'll close this issue as fixed. So sorry, I didn't know someone was working on this since it wasn;t assigned.

**Comment by ctoffanin** [comment]
Just checked right now. LGTM 👍

**Comment by Njong392** [comment]
Great! @TylerGeorgeAlexander is it okay to close this?

**Comment by TylerGeorgeAlexander** [comment]
Yup, sounds good.
