### ISSUE TITLE
ABBREVIATION: <NT>

### ISSUE THREAD

**Issue by Ameya02** [Njong392/Abbreve#371]
### Description

NT: Next Time

Please assign this to me

**Comment by Njong392** [comment]
> ### Description
> NT: Next Time TL: Team Lead
> 
> Please assign this to me

Hello. Thanks for opening this issue. But for now, we can only let you add NT. The second abbreviation won't really work out because abbreve is sort of an 'informal' dictionary. Hope you understand.
