### ISSUE TITLE
ABBREVIATION: <HNM>

### ISSUE THREAD

**Issue by EOluwaseun** [Njong392/Abbreve#372]
### Description

Happy New Month

**Comment by EOluwaseun** [comment]
I will like to add this abbreviation as my first contribution.. thanks!

**Comment by Njong392** [comment]
Yes, sure. I'm assigning you

**Comment by EOluwaseun** [comment]
Alright ! thanks, i will do just that..

**Comment by Njong392** [comment]
Closing this as fixed.
