### ISSUE TITLE
ABBREVIATION: <W/E>

### ISSUE THREAD

**Issue by Lekejosh** [Njong392/Abbreve#375]
### Description

Planning to add this abbreviation 'W/E' to the database, but whentrying to add 'w/e.json', a folder called 'w' is created with the file 'e.json' inside of it. How do I approach this?
![image](https://github.com/Njong392/Abbreve/assets/54216428/0710334c-0227-4a51-8170-382403fb5389)

**Comment by Njong392** [comment]
Hi there. Yes, this issue has been brought up before. I think I had some difficulties really getting the PR that was sent in for it, so I didn't merge it. For now, I can't really pinpoint a solution other than that we could try to reimplement what was done with node before to solve the issue. But the short-term solution so far has been to just avoid such abbreviations lmao 😂

**Comment by Lekejosh** [comment]
LMAO, Okay no problem. Thanks

**Comment by Njong392** [comment]
If you want to look deeper into this, here is the [PR](https://github.com/Njong392/Abbreve/pull/129) for reference. Maybe you'll understand better what was happening.

**Comment by Lekejosh** [comment]
Now, I understand, I see the reason why there is s%2Fo.json in the database, So you cancel the pull request because of the error on production
