### ISSUE TITLE
Tooltip on theme button shows icon name

### ISSUE THREAD

**Issue by gajanandh** [Njong392/Abbreve#380]
### Description

When hovered over dark mode and light mode buttons the tooltip shows moon and sunny. Is this a intended behaviour?

**Comment by Njong392** [comment]
Hello there! Thanks for the issue. That is the expected behaviour, but I think we could make the tooltips a but more descriptive. What do you think?

**Comment by gajanandh** [comment]
I have made changes to tooltip and made single button for theme. If this is ok I will raise a pull request .
![toggle~2](https://github.com/Njong392/Abbreve/assets/80502737/c24e4566-686c-43ca-9a0a-28d73e996771)
![toggleo~2](https://github.com/Njong392/Abbreve/assets/80502737/2befadbd-f415-48ff-99ac-9d53c497c7de)

https://github.com/Njong392/Abbreve/assets/80502737/ce98fdae-5a79-44a1-bb69-c92fbbcbf557
