### ISSUE TITLE
BUG: Theme toggle button does not work on first page load

### ISSUE THREAD

**Issue by gajanandh** [Njong392/Abbreve#383]
### Description

The theme toggle button does not work for first time when a new user visits page. When clicked on button it simple changes icon, actual theme does not change. Issue only occurs on first page visit. Can be reproduced by visiting page in incognito mode

**Comment by aviraj0010** [comment]
![Screenshot (159)](https://github.com/Njong392/Abbreve/assets/117421014/958a975f-0c02-46e8-bcec-4c952e8994ab)


JSON.parse(localStorage.getItem("toggleButton")) || false;   ====>  JSON.parse(localStorage.getItem("toggleButton")) || "false";

**Comment by Njong392** [comment]
Closing this as fixed
