### ISSUE TITLE
BUG: after failed search if you select whole text and delete, then search empty input it won't show error

### ISSUE THREAD

**Issue by data111a** [Njong392/Abbreve#387]
### Description

when I search maybe idgf, or something that is not in db, it shows error but when I select text and delete or ctrl+arrow and delete, then search this empty input it is not showing error that field is empty.

**Comment by rachit298** [comment]
Hi, I am new to open source. This issue seems interesting to me. Can someone guide me on how to start working on this? I have seen at a lot of places where we have to ask for "assign this issue to me". If this is the case, then please assign this to me.
