### ISSUE TITLE
SME: Subject Matter Expert

### ISSUE THREAD

**Issue by Rakshath66** [Njong392/Abbreve#413]
### Description

A common slang used in text, to refer a person as an expert in a particular subject.

Google Image Proof:-
![image](https://github.com/Njong392/Abbreve/assets/137169589/11cc50bd-ca21-49cb-bb62-c9638ffc473c)

**Comment by Njong392** [comment]
Abbreve is an unofficial dictionary for slang. Unfortunately, abbreviations like these don't fit in. Hope you understand.
