### ISSUE TITLE
FEATURE: make definitions shareable

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#417]
### Description

Currently, users can only lookup definitions, but it would also be great if there's a shareable link that users can share with others so they could easily view the definition instead of manually searching again

**Comment by trp02** [comment]
This is interesting. Maybe something like this.  
![image](https://github.com/Njong392/Abbreve/assets/83850231/2e7e0206-23f7-4b94-a0b5-575e19b8ecf8)

I would like to work on this

**Comment by Njong392** [comment]
This is interesting.... And this shareable link would lead to where? Back to the website with the search term already preentered?

**Comment by trp02** [comment]
That is exactly what I was thinking.

**Comment by Njong392** [comment]
@trp02 u mentioned that u want to work on this. Please open a draft pull request once assigned. This feature wasn't planned, and it sounds huge (kind of). I'd like to see how it pans out hehe

**Comment by Njong392** [comment]
Hey @trp02 how far with this? No pressure, just checking in

**Comment by trp02** [comment]
Hi, sorry for how long its taking. I've been swamped by school but I'm going to try to get a PR within a week or so.
