### ISSUE TITLE
BUG: Alignment between abbreviation and 'copied'

### ISSUE THREAD

**Issue by Njong392** [Njong392/Abbreve#422]
### Description

There is a small alignment issue between the abbreviation meaning and the 'copied' text. It would look a little better if these were perfectly aligned.

You can check the screenshot to see.

### Screenshots

![Screenshot (270)](https://github.com/Njong392/Abbreve/assets/81039882/f2da0286-51bd-44d5-9cd0-1cb6ff603544)

**Comment by Code-With-Hassan** [comment]
@Njong392 Assign this issue to me. I'll fix it.

**Comment by Njong392** [comment]
It's all yours.
