### ISSUE TITLE
The second card is being cut and overflowing on medium and small sized mobile screens.

### ISSUE THREAD

**Issue by Stephen-254** [Njong392/Abbreve#428]
### Description

The second card cuts and overflows in medium and small-size screens. 

### Screenshots

![Screenshot 2024-06-01 223102](https://github.com/Njong392/Abbreve/assets/106899176/57d4c304-b4ef-482a-a1db-f424dcc6f045)
![Screenshot 2024-06-01 223033](https://github.com/Njong392/Abbreve/assets/106899176/a92f4d17-3dff-4766-a6c4-2d9bb143262f)

**Comment by nehemiahh23** [comment]
Hi, is it alright if I work on this issue?

**Comment by Njong392** [comment]
> Hi, is it alright if I work on this issue?

Sincerest apologies for not replying to this issue sooner and assigning it, but a PR has already been opened it seems
