### ISSUE TITLE
Submit button searching for slang when input is empty

### ISSUE THREAD

**Issue by Superfly101** [Njong392/Abbreve#43]
### Description

when the search input is empty, hitting the submit button sends a request and all the abbreviations are fetched successfully but unable to find a matching abbreviation for the empty string '', hence resulting in the error message.

Adding input validation should fix this. Thank you, this is my first time creating an issue.

**Comment by Njong392** [comment]
Thank you for raising this :+1: Would you like to be assigned to fix this?

**Comment by Superfly101** [comment]
Yes, I would. Thank you

**Comment by Njong392** [comment]
Are you still working on this? A pull request has been opened for this already #72 I'll close it if you have already made progress on your side :+1:

**Comment by Superfly101** [comment]
I haven't had the time to work on this. So yeah, someone else can definitely take this.

**Comment by Njong392** [comment]
Closing this as solved.
