### ISSUE TITLE
BUG: UPPERCASE can't be written in the search bar.

### ISSUE THREAD

**Issue by Rohan-Nair** [Njong392/Abbreve#436]
### Description

On the search bar on the home page any text written in the search box turns to lowercase. 
Is this desired?

**Comment by joel-wlf** [comment]
I don't see why you would want to use uppercase. The search bar only using lowercase avoids confusion by end users which is why I think it's an intentional feature.

**Comment by Njong392** [comment]
Hello @Rohan-Nair Yes, this is done intentionally. It makes searching strict and easier, since we don't have start handling use cases such as when a user enters all caps or an abbreviation starting with caps, etc

**Comment by Rohan-Nair** [comment]
Like some abbreviations people see could be in all caps right? And they would try searching that way too. just a thought.  so this could be converted to lowercase later and let the user type whatever?

**Comment by joel-wlf** [comment]
Again, I don't think people would try to search for abbreviations, that include capital letters. And personally it would be very annoying when my keyboard constantly autocorrects me to a capital letter when I start typing.

**Comment by Rohan-Nair** [comment]
> Again, I don't think people would try to search for abbreviations, that include capital letters.

Why not? Aren't there many words which are abbreviated with all caps? 
ASAP
AFK 

I didn't get the other half of your comment but I'll close this issue now.
