### ISSUE TITLE
[FEATURE] Use prettier

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#45]
### Description

The current codebase is a bit hard to read because there is little/no linebreaks/formatting. Using prettier addresses this issue and would also help keep a consistent formatting for the whole codebase

### Screenshots

![Screenshot from 2022-10-03 23-27-50](https://user-images.githubusercontent.com/74247733/193703833-2916f48a-7887-406a-b630-d789e35d4958.png)
![Screenshot from 2022-10-03 23-29-34](https://user-images.githubusercontent.com/74247733/193703837-70ff5359-6178-4835-bb88-ca17599de5f7.png)

Before and After using prettier

**Comment by ctoffanin** [comment]
Yes, I was about to open the same!

**Comment by Njong392** [comment]
Oh yes. I have been thinking about this, and it's definitely on my list. @mathiasayivor do you want to create a branch and work on this? I assume we will be using `husky` to format on commit?

**Comment by Njong392** [comment]
> Yes, I was about to open the same!

Should I assign you to this @ctoffanin ? Since @mathiasayivor is taking on the migration issue.

**Comment by ctoffanin** [comment]
@Njong392, ask them first. If they're not up to it, assign it to me.

**Comment by mathiasayivor** [comment]
> > Yes, I was about to open the same!
> 
> Should I assign you to this @ctoffanin ? Since @mathiasayivor is taking on the migration issue.

Sure! @ctoffanin can be assigned.

**Comment by ctoffanin** [comment]
@Njong392 I have no time tonight. I will take care of it tomorrow morning!

**Comment by Njong392** [comment]
> @Njong392 I have no time tonight. I will take care of it tomorrow morning!

No problems. Do it when you can :+1:
