### ISSUE TITLE
[FEATURE] No Favicon

### ISSUE THREAD

**Issue by Superfly101** [Njong392/Abbreve#46]
### Description

The Logo used in the Navbar can also be up there as the favicon

**Comment by Njong392** [comment]
Could you please expatiate on this? Favicon as in how?

**Comment by Superfly101** [comment]
Sorry about that, a Favicon is simply the icon next to the title of a page.

For example, next to the page title which is "GitHub" the icon before it is called a favicon.
<img width="188" alt="github-favicon" src="https://user-images.githubusercontent.com/68870695/193765314-9afb12f6-196e-4c28-968f-ece733c8623b.png">

But next to the Abbreve title, there's no favicon it's blank.
<img width="288" alt="abbreve-favicon" src="https://user-images.githubusercontent.com/68870695/193765827-7d7068a7-4b9b-485a-9a2b-eb6a1faf946b.png">

Maybe you understand what I'm saying now?

**Comment by Njong392** [comment]
Oh, I see. Would you want to be assigned to this?

**Comment by Superfly101** [comment]
Yes, on it.
