### ISSUE TITLE
[OTHER]: Add hacktoberfest label

### ISSUE THREAD

**Issue by slim-codes** [Njong392/Abbreve#5]
### What would you like to share?

@Njong392 
Consider adding the hacktoberfest topic to this repo to bring more potential contributors to this project .
What do you think?

**Comment by Njong392** [comment]
Ah yes. I have thought of this. Thanks for bringing it up again. Now that you mention it, I think I should.

**Comment by Njong392** [comment]
I have successfully added the topic and label. I'll close this issue now. Thank you :tada:

**Comment by rupali-codes** [comment]
Hey @Njong392, You haven't added *Hacktoberfest* label yet.

**Comment by Njong392** [comment]
If a pull request is good enough for hacktoberfest, I'll add the label to the pull request itself. I removed the topic.
