### ISSUE TITLE
[DOCS] README.md contains Typos and Spelling mistakes 

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#54]
### Description

- In *Tech stack* section, there's a semicolon, it should be replaced with a Colon.
- In *steps* section, spelling of *repository* is incorrect.
- and some other small typos.

_No response_

**Comment by rupali-codes** [comment]
Hey @Njong392, I would like to work on this, kindly assign it to me :)

**Comment by Njong392** [comment]
Yes Rupali! Feel free to work on this. Assigning you.
