### ISSUE TITLE
[FEATURE] Form should be empty after clicking on submit

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#66]
### Description

Removing text after submitting form would be a nice option.

**Comment by Njong392** [comment]
I don't this would be very good UX. It would be nice to see the definition, alongside the input that the user made. But I would love to hear more thoughts on this.

**Comment by rupali-codes** [comment]
Well Emy, we are listening on Input events, and there's no need of submit button na, it's not going to do anything. 

More better, what we can do is showing reuslts If the word exists or not on Input (it says __ doesnt exist only when clicking on submit)

**Comment by Njong392** [comment]
> Well Emy, we are listening on Input events, and there's no need of submit button na, it's not going to do anything.
> 
> More better, what we can do is showing reuslts If the word exists or not on Input (it says __ doesnt exist only when clicking on submit)

We are currently addressing this issue. If we split the abbreviations into separate files, then the user will have to click submit every time they enter something. That way, if they click submit and a word doesn't exist, it will show.

**Comment by rupali-codes** [comment]
alright Emy :)
