### ISSUE TITLE
[FEATURE] Add husky

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#74]
### Description

Currently, we have prettier but you'd have to manually run `npm run format` to format the code base before pushing changes.
Sometimes, one might forget to format the code base before pushing changes.
Adding husky prevents this by automatically formatting the code base before each commit

**Comment by ctoffanin** [comment]
Good point! I'm used to the IDE's plugin that formats at every save. I forgot about it.

**Comment by mathiasayivor** [comment]
> And besides the formatting before committing, we can also run the lint pre-commit, right @mathiasayivor ? The code base is not huge. It won't take much time for the contributor.

yep

**Comment by Njong392** [comment]
Ah yes... `husky` totally skipped my mind when I reviewed the pull request. Does anyone want to take this on?
