### ISSUE TITLE
[FEATURE] UX: Add loading animation for searches

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#75]
### Description

Currently, there's no indication to show when the app is looking up the definition for my searched abbrev.
It would be an improvement in UX to show a loading animation when a search is running

**Comment by Njong392** [comment]
Good thinking. The response doesn't take more than 3 seconds to return, so adding a loading animation might be work for nothing.

**Comment by mathiasayivor** [comment]
> Good thinking. The response doesn't take more than 3 seconds to return (for me it doesn't), so adding a loading animation might be work for nothing.

IMO, it's generally a good idea to add indicators for running processes, even if they take only a few ms
In this case, the delay might be noticed by users with a slow connection or even those that lost their connection whiles searching.

**Comment by Njong392** [comment]
Sure thing @ctoffanin go ahead and take it.

**Comment by ctoffanin** [comment]
I didn't flee! I'm having some trouble with CSS (well, not a surprise 😄). 
If I can't figure stuff out, I'll make a PR and somebody will help me from there.

**Comment by Njong392** [comment]
You can always open a draft pull request and we'll fix it from there. I'm sure your work will be great Cristian.
