### ISSUE TITLE
[FEATURE] UX: Show search suggestions for similar abbrevs when searching

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#76]
### Description

It would be great to show search suggestions for similar abbrevs when the user starts typing in the search box.

### Additional information

Sometimes, you may forget an abbrev but you know the first few characters. Adding search suggestions provides a good ux in such situations

**Comment by Njong392** [comment]
Here's why I think this might not be a big worry for now. I am assuming that people would visit the site because they have something specific they are looking for. I see the point you are making here though.

**Comment by mathiasayivor** [comment]
Sure... makes sense
