### ISSUE TITLE
When hovering on *Get Started* button, it's text-color is Not looking good

### ISSUE THREAD

**Issue by rupali-codes** [Njong392/Abbreve#83]
### Description

Text color of *Get Started* button should be updated to white

### Screenshots

On Hover
![image](https://user-images.githubusercontent.com/78981177/194132776-ae46f697-daf8-4e6a-a1be-671507162721.png)

### Additional information

I'll appriciate if this can be assinged to me ;)

**Comment by Njong392** [comment]
Is this the color when you hover?

**Comment by Njong392** [comment]
This issue is a duplicate of #78 so I'll have to close it unfortunately.
