### ISSUE TITLE
[FEATURE] UX: UI v2

### ISSUE THREAD

**Issue by mathiasayivor** [Njong392/Abbreve#86]
### Description

Currently, users have to scroll down in order to search for abbreviations, which IMO is not a good UX since the main focus of the app is for users to quickly find definitions for abbrevs.

My proposal is to move the search input to the top so that users can easily and quickly search for abbrev definitions.

### Screenshots

![Screenshot 2022-10-06 at 00-09-41 Abbreve](https://user-images.githubusercontent.com/74247733/194186461-fdec61d6-c554-4a30-b0b9-c131c58991ab.png)
As you can see, the search input + button is visible the moment the user opens the app without even scrolling down

**Comment by mathiasayivor** [comment]
@Njong392 @adropofilm Any views on this?

**Comment by adropofilm** [comment]
Definitely agree. I also think this should be moved up too, since it won't make sense to have it at the bottom when the search bar is moved up.

![Screen Shot 2022-10-09 at 2 36 01 PM](https://user-images.githubusercontent.com/9134674/194776163-872c6ba8-89e8-4337-ae09-926d02e65078.jpg)

**Comment by Njong392** [comment]
Yes, I think we should move the entire component upward as @adropofilm has suggested. Is anyone up for this issue?

**Comment by prakashrx** [comment]
@Njong392 Can you assign to me
