### ISSUE TITLE
[DOCS] Add automatic releases

### ISSUE THREAD

**Issue by Dun-sin** [Njong392/Abbreve#90]
### Description

I noticed that the last time a release for this project was done, it was over 2 years ago.

How about create an automatic release, that happens whenever some contributes to this project, it will use the conventional commit.

Here's a link for reference: 
[Set Automatic Release (Skip Commitizen)](https://youtu.be/QZdY4XYbqLI)
[Conventional Commit](https://gist.github.com/Zekfad/f51cb06ac76e2457f11c80ed705c95a3)

> ## This can only be done by the owner of the repo

**Comment by Njong392** [comment]
Yayyy! Thank you for bringing this up. Fixed :tada:
