### ISSUE TITLE
[DOCS] Use a gif to show a demo

### ISSUE THREAD

**Issue by Dun-sin** [Njong392/Abbreve#91]
### Description

Instead of a picture of the website for demo in the readme, would be nice to have a gif instead

**Comment by Dun-sin** [comment]
> Hi Dunsin, great idea. Do you want me to assign this to you?

Na, I'm good, someone else can take it

**Comment by Njong392** [comment]
> Awesome, will work on it asap

Awesome! I'll assign this issue to you 💙💙

**Comment by TheZal** [comment]
Can u please add the hacktoberfest-approved label? I saw this issue thanks to the hacktoberfest!

**Comment by Njong392** [comment]
> Can u please add the hacktoberfest-approved label? I saw this issue thanks to the hacktoberfest!

Done. I added the label after it was merged, so please tell me if it does or does not appear in your hacktoberfest profile.

**Comment by TheZal** [comment]
Yes, it appears! Thx
