### ISSUE TITLE
[DOCS] Update instructions for adding new abbreviations

### ISSUE THREAD

**Issue by adropofilm** [Njong392/Abbreve#92]
### What would you like to share?

We need to update the repo README.md to account for the changes made in https://github.com/Njong392/Abbreve/pull/64.

**Comment by adropofilm** [comment]
@mathiasayivor do you want to take this over?

**Comment by Njong392** [comment]
Since this is somewhat crucial, once I change the structure, I'll immediately change the README too.

**Comment by adropofilm** [comment]
Sounds good @Njong392 @mathiasayivor
