### ISSUE TITLE
[OTHER]-CONFLICTING ABBREVIATIONS

### ISSUE THREAD

**Issue by theselaw** [Njong392/Abbreve#99]
### What would you like to share?

CONFLICTING ABBREVIATIONS

### Additional information

I think room should be made for some abbr. terms like "WTH" which has more than one meaning i.e " What the heck" and "What the hell".

**Comment by adropofilm** [comment]
Hi @theselaw! Great suggestion. We currently cover this with the `alternatives` key for abbreviations that may have more than one meaning. You can find some examples of this elaborated in the [`db.json`](https://github.com/Njong392/Abbreve/blob/b032878231d10f1ac9892981aa912dd745c971da/public/server/db.json#L3).

**Comment by theselaw** [comment]
Alright!,Saw that, great.
